### PR TITLE
hard code progress bar colors

### PR DESCRIPTION
**Pull request by jwong-d2l**

### CODE REVIEW

**Comment by benyamin-noori** [comment]
Looks like some of the tests are still failing.

**Comment by benyamin-noori** [comment]
Why are we hard coding it? Old way seems better... right?

**Comment by dbatiste** [comment]
Not sure if it fits into the design of this stuff, but we have some reusable progress-bar styles in [d2l-progress](https://github.com/BrightspaceUI/progress).

**Comment by jwong-d2l** [comment]
@benyamin-noori it was a Nick decision.

**Pull request merged**
